modLoader="javafml"
loaderVersion="[36,)"

issueTrackerURL="https://github.com/c0d3break3r/TheHallow/issues"
license="Pugz, All Rights Reserved"

[[mods]]
    modId="hallows"
    version="0.0.1"
    logoFile="TheHallow.png"
    displayName="The Hallow"
    authors="Pugz"
    credits=""
    description='''A spoooky new dimension 0_0'''

[[dependencies.hallows]]
    modId="forge"
    mandatory=true
    versionRange="[34.1.42,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.hallows]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3,1.17)"
    ordering="NONE"
    side="BOTH"

[[dependencies.hallows]]
    modId="abnormals_core"
    mandatory=true
    versionRange="[3.1.0,)"
    ordering="AFTER"
    side="BOTH"